### ISSUE TITLE
Webgpu 

### ISSUE THREAD

**Issue by robbisy** [gfxfundamentals/webgl2-fundamentals#77]
Not an issue just a question 
Will you do a webgpu-fundamentals ?
Mozilla have started to implent it a few month ago : https://hacks.mozilla.org/2020/04/experimental-webgpu-in-firefox/

**Comment by greggman** [comment]
[I've thought about it](https://github.com/gfxfundamentals/webgpu) but until they actually ship a version with the final shader language it's kind of a waste to start. Basically anything written will have to be re-written.

I'm also a little worried since I didn't personally work on WebGPU I'm not nearly as comfortable with it. But in general it's mostly the same. You still set up buffers, attributes, textures, shader, uniforms, the concepts are all the same. The only difference is the API so most of the things you need to know are the same (how to write a shader, how to use matrices, how to compute lighting, ...)
